spring:
  config:
    import: "configserver:"
  application:
    name: api-gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    urls:
      - name: Identity Service
        url: /v3/api-docs/identity-service
      - name: Profile Service
        url: /v3/api-docs/profile-service
      - name: Wallet Service
        url: /v3/api-docs/wallet-service
      - name: Marketplace Service
        url: /v3/api-docs/marketplace-service
      - name: Flashcard Service
        url: /v3/api-docs/flashcard-service
      - name: Quiz Service
        url: /v3/api-docs/quiz-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
      - name: Reward Service
        url: /v3/api-docs/reward-service
  api-docs:
    path: /v3/api-docs

server:
  port: ${GATEWAY_PORT:8080}
